spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true

grpc:
  server:
    port: 9090
    security:
      enabled: false
