spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/auth_db
    username: auth_user
    password: auth_password
  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true

grpc:
  server:
    port: 9090
    security:
      enabled: false

app:
  jwt:
    secret: MySuperSecretKey1234567890ABCBACABCdef4567890123456789012345678901234567890
    expiration-ms: 86400000
